/* Algorithm-independent map view. It consumes visualization snapshots only.
 * frontier: pending node IDs; visited: processed IDs; current: expanding node;
 * checking: neighbour; activeEdge: canonical edge key; path: final route.
 * There is deliberately no BFS/DFS/A* traversal logic in this file. */
(() => {
 const PQ = globalThis.PathQuest;
 PQ.createMapView = function({container, graph}) {
  container.innerHTML = MAP_SVG;
  const $ = id => document.getElementById(id);
  const svg = $('city-map'), ns = 'http://www.w3.org/2000/svg';
  const {nodes:NODES, edges:EDGES, byId:BY_ID, adjacency:ADJ} = graph;
  const edgeKey=PQ.edgeKey;
  let snapshot=null,view={x:0,y:0,w:1120,h:720},drag=null;
 function pathFor(a,b){const p=BY_ID[a],q=BY_ID[b];if(Math.abs(p.x-q.x)>100){const mid=(p.x+q.x)/2;return `M${p.x},${p.y} L${mid-14},${p.y} Q${mid},${p.y} ${mid},${(p.y+q.y)/2} Q${mid},${q.y} ${mid+14},${q.y} L${q.x},${q.y}`}const mid=(p.y+q.y)/2;return `M${p.x},${p.y} L${p.x},${mid-12} Q${p.x},${mid} ${(p.x+q.x)/2},${mid} Q${q.x},${mid} ${q.x},${mid+12} L${q.x},${q.y}`}
 const roadSVG=[],highlightSVG=[];
 EDGES.forEach(([a,b])=>{const d=pathFor(a,b),avenue=['F-G','G-H','H-I','I-J','P-Q','Q-R','R-S','S-T'].includes(edgeKey(a,b));roadSVG.push(`<path d="${d}" fill="none" stroke="#cbd0bf" stroke-width="${avenue?18:14}" stroke-linecap="round" stroke-linejoin="round"/><path d="${d}" fill="none" stroke="${avenue?'#fff4c4':'#fffef8'}" stroke-width="${avenue?14:10}" stroke-linecap="round" stroke-linejoin="round"/>`);highlightSVG.push(`<path id="edge-${edgeKey(a,b)}" class="road-highlight" d="${d}"/>`)});
 $('roads').innerHTML=roadSVG.join('');$('edge-highlights').innerHTML=highlightSVG.join('');
 NODES.forEach(n=>{const g=document.createElementNS(ns,'g');g.id='node-'+n.id;g.setAttribute('class','place-node');g.setAttribute('transform',`translate(${n.x} ${n.y})`);g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',n.name+'; node '+n.id);g.innerHTML=`<title>${n.id} · ${n.name}</title><circle class="halo" r="25"/><circle class="node-core" r="15"/><text class="node-letter" y="0">${n.id}</text><text class="place-label" y="35">${n.name}</text><text class="badge-label" y="-33"></text>`;g.addEventListener('click',()=>showNode(n));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showNode(n)}});$('map-nodes').appendChild(g)});
 function showNode(n){const s=snapshot,status=s?.visited.includes(n.id)?'Visited':s?.discovered.includes(n.id)?'In queue':'Unvisited';$('map-tooltip').textContent=`${n.id} · ${n.name} · ${status} · Neighbours: ${ADJ[n.id].join(', ')}${s?.scores?.[n.id]?' · g='+s.scores[n.id].g+' h='+s.scores[n.id].h+' f='+s.scores[n.id].f:''}`;$('map-tooltip').classList.add('show')}

 function render(s, {start:selectedStart, end:selectedEnd}) {
  snapshot=s;
  const queue=s?.frontier||[],visited=s?.visited||[],path=s?.path||[];
  NODES.forEach(n=>{const g=$('node-'+n.id),isCurrent=s?.current===n.id&&!(['found','route'].includes(s?.kind)),isChecking=s?.checking===n.id;let state='unvisited';if(queue.includes(n.id))state='queued';if(visited.includes(n.id))state='visited';if(isChecking)state='checking';if(isCurrent)state='current';if(path.includes(n.id))state='on-path';g.setAttribute('class',`place-node ${state}${n.id===selectedStart?' start':''}${n.id===selectedEnd?' goal':''}`);g.querySelector('.badge-label').textContent=n.id===selectedStart&&n.id===selectedEnd?'START / END':n.id===selectedStart?'START':n.id===selectedEnd?'END':'';g.querySelector('.node-letter').textContent=visited.includes(n.id)&&!isCurrent&&!path.includes(n.id)?'✓':n.id;g.setAttribute('aria-label',`${n.id}, ${n.name}, ${state}`)});
  EDGES.forEach(([a,b])=>{const k=edgeKey(a,b),el=$('edge-'+k);let cls='road-highlight';if(s?.activeEdge===k)cls+=' active';for(let i=1;i<path.length;i++)if(edgeKey(path[i-1],path[i])===k)cls='road-highlight path';el.setAttribute('class',cls)});

 }
 // SVG viewBox supplies dependency-free zoom and drag. Clamp to city bounds.
 function adaptLabels(){const box=svg.getBoundingClientRect(),scale=Math.min(box.width/view.w,box.height/view.h);if(!scale)return;NODES.forEach(n=>{const g=$('node-'+n.id),r=Math.max(15,11/scale);g.querySelector('.node-core').setAttribute('r',r);g.querySelector('.halo').setAttribute('r',Math.max(25,18/scale));g.querySelector('.node-letter').style.fontSize=Math.max(12,12/scale)+'px';const label=g.querySelector('.place-label');label.style.fontSize=Math.max(12,12/scale)+'px';label.setAttribute('y',r+18/scale);label.style.display=scale<.48?'none':'';g.querySelector('.badge-label').style.fontSize=Math.max(9,10/scale)+'px';g.querySelector('.badge-label').setAttribute('y',-r-12/scale)});document.querySelector('.map-sub').textContent=scale<.48?'Fictional map · zoom in for place names':'Fictional learning map · drag to explore'}
 function updateView(){view.x=Math.max(-200,Math.min(1320-view.w,view.x));view.y=Math.max(-100,Math.min(820-view.h,view.y));svg.setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);adaptLabels()}
 function zoom(factor){const nw=Math.max(360,Math.min(1400,view.w*factor)),nh=nw*720/1120;view.x+=(view.w-nw)/2;view.y+=(view.h-nh)/2;view.w=nw;view.h=nh;updateView()}
 $('zoom-in').addEventListener('click',()=>zoom(.8));$('zoom-out').addEventListener('click',()=>zoom(1.25));$('fit').addEventListener('click',()=>{view={x:0,y:0,w:1120,h:720};updateView()});
 const stage=$('map-stage');stage.addEventListener('pointerdown',e=>{if(e.target.closest('.place-node'))return;drag={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y,id:e.pointerId};stage.setPointerCapture(e.pointerId);stage.classList.add('dragging');$('map-tooltip').classList.remove('show')});stage.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const rect=svg.getBoundingClientRect(),scale=Math.max(view.w/rect.width,view.h/rect.height);view.x=drag.vx-(e.clientX-drag.x)*scale;view.y=drag.vy-(e.clientY-drag.y)*scale;updateView()});function endDrag(){drag=null;stage.classList.remove('dragging')}stage.addEventListener('pointerup',endDrag);stage.addEventListener('pointercancel',endDrag);stage.addEventListener('lostpointercapture',endDrag);

 const resizeObserver=new ResizeObserver(adaptLabels);
 resizeObserver.observe(container);
 adaptLabels();
 return {render, clearTooltip:()=> $('map-tooltip').classList.remove('show')};
 };
 const MAP_SVG = `<svg id="city-map" viewBox="0 0 1120 720" role="img" aria-labelledby="map-title map-description"><title id="map-title">Lakeview City road network</title><desc id="map-description">Twenty places linked by two-way roads. Node colours and symbols show the queue, visited places and the route found by the selected algorithm.</desc><defs><pattern id="blocks" width="190" height="150" patternUnits="userSpaceOnUse"><rect width="190" height="150" fill="#e9edde"/><rect x="12" y="12" width="55" height="30" rx="3" fill="#e1e6d8"/><rect x="75" y="12" width="38" height="30" rx="3" fill="#e0e5d7"/><rect x="122" y="12" width="53" height="30" rx="3" fill="#e0e5d7"/><rect x="12" y="52" width="46" height="58" rx="4" fill="#dfe5d8"/><rect x="68" y="52" width="107" height="58" rx="4" fill="#e0e5d8"/><path d="M0 122H190M183 0V150" stroke="#f6f7ef" stroke-width="7"/></pattern></defs><g id="world"><rect x="-1300" y="-1000" width="3800" height="2800" fill="url(#blocks)"/><g id="terrain"><path d="M726 -80 C682 110 834 158 785 275 S734 440 806 540 S839 711 800 830 L894 830 C939 696 920 617 870 519 S821 356 860 261 S797 74 805 -80Z" fill="#b7dce7"/><path d="M726 -80 C682 110 834 158 785 275 S734 440 806 540 S839 711 800 830" fill="none" stroke="#a2d0d4" stroke-width="3"/><path d="M52 286Q51 250 98 247L236 247Q265 250 260 284L247 355Q234 375 185 369L89 367Q54 361 52 326Z" fill="#c8dfb7"/><path d="M59 297Q141 265 241 304M91 357Q135 300 240 270" fill="none" stroke="#e5eed8" stroke-width="5"/><rect x="462" y="451" width="213" height="73" rx="21" fill="#c6deb4"/><path d="M477 486H657M546 461V513" stroke="#e7efd9" stroke-width="5"/><rect x="890" y="242" width="165" height="123" rx="14" fill="#d3e3bc"/><ellipse cx="1000" cy="488" rx="74" ry="39" fill="#cbdcb8"/><ellipse cx="1000" cy="488" rx="55" ry="27" fill="none" stroke="#e7eddc" stroke-width="9"/><path d="M25 652 Q340 656 501 672 T1090 657" stroke="#d9d3b8" stroke-width="6" fill="none"/><path d="M25 652 Q340 656 501 672 T1090 657" stroke="#faf4d6" stroke-width="3" fill="none"/></g><g id="district-labels" fill="#8c9b80" font-size="11" font-weight="650" letter-spacing="3"><text x="68" y="95">LAKEVIEW</text><text x="415" y="83">OLD TOWN</text><text x="911" y="85">EAST BANK</text><text x="43" y="543">WEST END</text><text x="482" y="559">GARDEN DISTRICT</text></g><g id="roads"></g><g fill="#8b9987" font-size="10" font-style="italic"><text x="217" y="148">Lakeview Road</text><text x="384" y="329">Central Avenue</text><text x="607" y="183">Museum Road</text><text x="381" y="599">South Street</text><text x="824" y="675" fill="#6d9eaa" transform="rotate(-75 824 675)">Willow River</text><text x="113" y="315" fill="#75955d">Willow Park</text><text x="512" y="500" fill="#75955d">Botanical Garden</text></g><g id="edge-highlights"></g><g id="map-nodes"></g></g></svg>`;
})();
